class_name BuildCatalog
extends RefCounted
## Single source of truth for what build mode can place: id, category,
## label. hud.gd builds the palette FROM this table at runtime instead of
## hardcoding a GridContainer per category in hud.tscn, so adding a
## placeable — or a whole new category — is a data change here, not a scene
## edit.
##
## Today every category is dev_only: this is still the Fase 2 mapping tool
## (mobs/resources/POIs), not something a player should see. The split
## world_zone.gd's build-mode section describes — this same place->save->
## reload loop becoming a player-facing construction mode (structures,
## decoration) — is meant to happen by adding new categories here with
## dev_only = false, and having whatever player-facing entry point filters
## the palette to non-dev_only categories. No such entry point exists yet;
## this is the extension point for when one does.

## Category id -> {label, dev_only}, in palette display order.
const CATEGORIES := [
	["mob", {"label": "MOBS", "dev_only": true}],
	["resource", {"label": "RECURSOS", "dev_only": true}],
	["poi", {"label": "POIS", "dev_only": true}],
	["structure", {"label": "ESTRUCTURA", "dev_only": true}],
	["roof", {"label": "TECHO (pintar)", "dev_only": true}],
	["camino", {"label": "CAMINO (auto)", "dev_only": true}],
	["pincel", {"label": "PINCEL (libre)", "dev_only": true}],
	["suelo", {"label": "SUELO (pintar)", "dev_only": true}],
	["decor", {"label": "DECORACIÓN", "dev_only": true}],
	["building", {"label": "EDIFICIOS (prefab)", "dev_only": true}],
	["collision", {"label": "COLISIÓN", "dev_only": true}],
]

## Placeable id -> {category, label}, in palette display order within its
## category. The id is what ZoneBuilder/world_zone.gd's _instantiate_marker()
## and BuildIcons both key off.
const ENTRIES := [
	["mob", {"category": "mob", "label": "Mob"}],
	["tree", {"category": "resource", "label": "Árbol"}],
	["rock", {"category": "resource", "label": "Roca"}],
	["vein", {"category": "resource", "label": "Vena de hierro"}],
	["vendor", {"category": "poi", "label": "POI: Vendor"}],
	["bank", {"category": "poi", "label": "POI: Bank"}],
	["repair", {"category": "poi", "label": "POI: Repair"}],
	["dungeon_entrance", {"category": "poi", "label": "POI: Entrada dungeon"}],
	["mini_boss", {"category": "poi", "label": "POI: Mini-boss"}],
	["wall_n", {"category": "structure", "label": "Pared (frente/N)"}],
	["wall_e", {"category": "structure", "label": "Pared (este)"}],
	["wall_s", {"category": "structure", "label": "Pared (sur/fachada)"}],
	["wall_w", {"category": "structure", "label": "Pared (oeste)"}],
	["corner_out_ne", {"category": "structure", "label": "Esquina ext. NE"}],
	["corner_out_nw", {"category": "structure", "label": "Esquina ext. NW"}],
	["corner_out_se", {"category": "structure", "label": "Esquina ext. SE"}],
	["corner_out_sw", {"category": "structure", "label": "Esquina ext. SW"}],
	["corner_in_ne", {"category": "structure", "label": "Esquina int. NE"}],
	["corner_in_nw", {"category": "structure", "label": "Esquina int. NW"}],
	["corner_in_se", {"category": "structure", "label": "Esquina int. SE"}],
	["corner_in_sw", {"category": "structure", "label": "Esquina int. SW"}],
	["partition_n", {"category": "structure", "label": "Pared interior (N)"}],
	["partition_e", {"category": "structure", "label": "Pared interior (E)"}],
	["partition_s", {"category": "structure", "label": "Pared interior (S)"}],
	["partition_w", {"category": "structure", "label": "Pared interior (O)"}],
	["partition_hub", {"category": "structure", "label": "Cruce de paredes interiores"}],
	["column", {"category": "structure", "label": "Columna"}],
	["floor", {"category": "structure", "label": "Piso interior"}],
	["door", {"category": "structure", "label": "Puerta (click en pared)"}],
	["window_arched", {"category": "structure", "label": "Ventana arqueada (click en pared)"}],
	["window_small", {"category": "structure", "label": "Ventana chica (click en pared)"}],
	["window_medium", {"category": "structure", "label": "Ventana mediana (click en pared)"}],
	["window_large", {"category": "structure", "label": "Ventana grande (click en pared)"}],
	["window_flowerbox", {"category": "structure", "label": "Ventana con flores (click en pared)"}],
	["torch", {"category": "structure", "label": "Antorcha (click en pared)"}],
	["roof_eave_n", {"category": "roof", "label": "Techo: alero N"}],
	["roof_eave_e", {"category": "roof", "label": "Techo: alero E"}],
	["roof_eave_s", {"category": "roof", "label": "Techo: alero S"}],
	["roof_eave_w", {"category": "roof", "label": "Techo: alero O"}],
	["roof_hip_ne", {"category": "roof", "label": "Techo: límatesa NE"}],
	["roof_hip_nw", {"category": "roof", "label": "Techo: límatesa NW"}],
	["roof_hip_se", {"category": "roof", "label": "Techo: límatesa SE"}],
	["roof_hip_sw", {"category": "roof", "label": "Techo: límatesa SW"}],
	["roof_valley_ne", {"category": "roof", "label": "Techo: limahoya NE"}],
	["roof_valley_nw", {"category": "roof", "label": "Techo: limahoya NW"}],
	["roof_valley_se", {"category": "roof", "label": "Techo: limahoya SE"}],
	["roof_valley_sw", {"category": "roof", "label": "Techo: limahoya SW"}],
	["roof_ridge_ew", {"category": "roof", "label": "Techo: cumbrera E-O"}],
	["roof_ridge_ns", {"category": "roof", "label": "Techo: cumbrera N-S"}],
	["roof_end_n", {"category": "roof", "label": "Techo: remate N"}],
	["roof_end_e", {"category": "roof", "label": "Techo: remate E"}],
	["roof_end_s", {"category": "roof", "label": "Techo: remate S"}],
	["roof_end_w", {"category": "roof", "label": "Techo: remate O"}],
	["roof_pyramid", {"category": "roof", "label": "Techo: pirámide"}],
	["roof_interior", {"category": "roof", "label": "Techo: campo"}],
	["decor_plains_ground_flowers", {"category": "suelo", "label": "Plains: Pasto con flores (10x3)"}],
	["decor_plains_ground_dirt", {"category": "suelo", "label": "Plains: Parche de tierra (6x6)"}],
	["decor_plains_pond", {"category": "suelo", "label": "Plains: Estanque (6x6)"}],
	["decor_plains_water", {"category": "suelo", "label": "Plains: Agua (5x3)"}],
	["decor_plains_bridge_v", {"category": "suelo", "label": "Plains: Puente vertical"}],
	["decor_plains_bridge_h", {"category": "suelo", "label": "Plains: Puente horizontal"}],
	["decor_plains_plateau_dirt", {"category": "suelo", "label": "Plains: Meseta con barranca"}],
	["decor_plains_plateau_stone", {"category": "suelo", "label": "Plains: Isla rocosa (10x8)"}],
	["decor_plains_shore", {"category": "suelo", "label": "Plains: Orilla (4x5)"}],
	# One brush per road style instead of one button per piece: the cell
	# picks its own tile from its neighbours (see RoadAutotiler), which is
	# what makes a curve or a diagonal drawable at all. The 200-odd
	# "floor_road_*" ids below are the same art, still exposed piece by
	# piece under SUELO for when a specific tile is wanted.
	#
	# Only the styles whose edge art actually REPEATS along a run are here —
	# "madera" and "losa" are framed platforms in this pack and come out as
	# stacked boxes down a long road, so they stay SUELO-only. That list is
	# decided by measurement in tools/bake_road_autotile.py, not here;
	# validate_road_autotile.gd fails if these entries drift from it.
	# The free brush: no grid, no autotile, no marker per cell — it paints a
	# coverage mask and a shader cuts a repeating texture out of it (see
	# PaintLayer). For worn dirt tracks and clearings, the things that are not
	# BUILT and so have no business snapping to a 32px cell.
	["paint_tierra", {"category": "pincel", "label": "Pincel: Tierra"}],
	["paint_pasto", {"category": "pincel", "label": "Pincel: Pasto"}],
	["paint_agua", {"category": "pincel", "label": "Pincel: Agua"}],
	["paint_adoquin", {"category": "pincel", "label": "Pincel: Adoquín"}],
	["paint_ladrillo", {"category": "pincel", "label": "Pincel: Ladrillo"}],
	["paint_piedra", {"category": "pincel", "label": "Pincel: Piedra"}],
	["paint_losa", {"category": "pincel", "label": "Pincel: Losa"}],
	["paint_madera", {"category": "pincel", "label": "Pincel: Madera"}],
	["floor_autoroad_adoquin", {"category": "camino", "label": "Camino auto: Adoquín"}],
	["floor_autoroad_ladrillo", {"category": "camino", "label": "Camino auto: Ladrillo"}],
	["floor_autoroad_piedra", {"category": "camino", "label": "Camino auto: Piedra"}],
	["floor_road_adoquin_01", {"category": "suelo", "label": "Camino Adoquín 1"}],
	["floor_road_adoquin_02", {"category": "suelo", "label": "Camino Adoquín 2"}],
	["floor_road_adoquin_03", {"category": "suelo", "label": "Camino Adoquín 3"}],
	["floor_road_adoquin_04", {"category": "suelo", "label": "Camino Adoquín 4"}],
	["floor_road_adoquin_05", {"category": "suelo", "label": "Camino Adoquín 5"}],
	["floor_road_adoquin_06", {"category": "suelo", "label": "Camino Adoquín 6"}],
	["floor_road_adoquin_07", {"category": "suelo", "label": "Camino Adoquín 7"}],
	["floor_road_adoquin_08", {"category": "suelo", "label": "Camino Adoquín 8"}],
	["floor_road_adoquin_09", {"category": "suelo", "label": "Camino Adoquín 9"}],
	["floor_road_adoquin_10", {"category": "suelo", "label": "Camino Adoquín 10"}],
	["floor_road_adoquin_11", {"category": "suelo", "label": "Camino Adoquín 11"}],
	["floor_road_adoquin_12", {"category": "suelo", "label": "Camino Adoquín 12"}],
	["floor_road_adoquin_13", {"category": "suelo", "label": "Camino Adoquín 13"}],
	["floor_road_adoquin_14", {"category": "suelo", "label": "Camino Adoquín 14"}],
	["floor_road_adoquin_15", {"category": "suelo", "label": "Camino Adoquín 15"}],
	["floor_road_adoquin_16", {"category": "suelo", "label": "Camino Adoquín 16"}],
	["floor_road_adoquin_17", {"category": "suelo", "label": "Camino Adoquín 17"}],
	["floor_road_adoquin_18", {"category": "suelo", "label": "Camino Adoquín 18"}],
	["floor_road_adoquin_19", {"category": "suelo", "label": "Camino Adoquín 19"}],
	["floor_road_adoquin_20", {"category": "suelo", "label": "Camino Adoquín 20"}],
	["floor_road_adoquin_21", {"category": "suelo", "label": "Camino Adoquín 21"}],
	["floor_road_adoquin_22", {"category": "suelo", "label": "Camino Adoquín 22"}],
	["floor_road_adoquin_23", {"category": "suelo", "label": "Camino Adoquín 23"}],
	["floor_road_adoquin_24", {"category": "suelo", "label": "Camino Adoquín 24"}],
	["floor_road_adoquin_25", {"category": "suelo", "label": "Camino Adoquín 25"}],
	["floor_road_adoquin_26", {"category": "suelo", "label": "Camino Adoquín 26"}],
	["floor_road_adoquin_27", {"category": "suelo", "label": "Camino Adoquín 27"}],
	["floor_road_adoquin_28", {"category": "suelo", "label": "Camino Adoquín 28"}],
	["floor_road_adoquin_29", {"category": "suelo", "label": "Camino Adoquín 29"}],
	["floor_road_adoquin_30", {"category": "suelo", "label": "Camino Adoquín 30"}],
	["floor_road_adoquin_31", {"category": "suelo", "label": "Camino Adoquín 31"}],
	["floor_road_adoquin_32", {"category": "suelo", "label": "Camino Adoquín 32"}],
	["floor_road_adoquin_33", {"category": "suelo", "label": "Camino Adoquín 33"}],
	["floor_road_adoquin_34", {"category": "suelo", "label": "Camino Adoquín 34"}],
	["floor_road_adoquin_35", {"category": "suelo", "label": "Camino Adoquín 35"}],
	["floor_road_adoquin_36", {"category": "suelo", "label": "Camino Adoquín 36"}],
	["floor_road_adoquin_37", {"category": "suelo", "label": "Camino Adoquín 37"}],
	["floor_road_adoquin_38", {"category": "suelo", "label": "Camino Adoquín 38"}],
	["floor_road_adoquin_39", {"category": "suelo", "label": "Camino Adoquín 39"}],
	["floor_road_adoquin_40", {"category": "suelo", "label": "Camino Adoquín 40"}],
	["floor_road_adoquin_41", {"category": "suelo", "label": "Camino Adoquín 41"}],
	["floor_road_adoquin_42", {"category": "suelo", "label": "Camino Adoquín 42"}],
	["floor_road_adoquin_43", {"category": "suelo", "label": "Camino Adoquín 43"}],
	["floor_road_adoquin_44", {"category": "suelo", "label": "Camino Adoquín 44"}],
	["floor_road_adoquin_45", {"category": "suelo", "label": "Camino Adoquín 45"}],
	["floor_road_adoquin_46", {"category": "suelo", "label": "Camino Adoquín 46"}],
	["floor_road_adoquin_47", {"category": "suelo", "label": "Camino Adoquín 47"}],
	["floor_road_adoquin_48", {"category": "suelo", "label": "Camino Adoquín 48"}],
	["floor_road_adoquin_49", {"category": "suelo", "label": "Camino Adoquín 49"}],
	["floor_road_ladrillo_01", {"category": "suelo", "label": "Camino Ladrillo 1"}],
	["floor_road_ladrillo_02", {"category": "suelo", "label": "Camino Ladrillo 2"}],
	["floor_road_ladrillo_03", {"category": "suelo", "label": "Camino Ladrillo 3"}],
	["floor_road_ladrillo_04", {"category": "suelo", "label": "Camino Ladrillo 4"}],
	["floor_road_ladrillo_05", {"category": "suelo", "label": "Camino Ladrillo 5"}],
	["floor_road_ladrillo_06", {"category": "suelo", "label": "Camino Ladrillo 6"}],
	["floor_road_ladrillo_07", {"category": "suelo", "label": "Camino Ladrillo 7"}],
	["floor_road_ladrillo_08", {"category": "suelo", "label": "Camino Ladrillo 8"}],
	["floor_road_ladrillo_09", {"category": "suelo", "label": "Camino Ladrillo 9"}],
	["floor_road_ladrillo_10", {"category": "suelo", "label": "Camino Ladrillo 10"}],
	["floor_road_ladrillo_11", {"category": "suelo", "label": "Camino Ladrillo 11"}],
	["floor_road_ladrillo_12", {"category": "suelo", "label": "Camino Ladrillo 12"}],
	["floor_road_ladrillo_13", {"category": "suelo", "label": "Camino Ladrillo 13"}],
	["floor_road_ladrillo_14", {"category": "suelo", "label": "Camino Ladrillo 14"}],
	["floor_road_ladrillo_15", {"category": "suelo", "label": "Camino Ladrillo 15"}],
	["floor_road_ladrillo_16", {"category": "suelo", "label": "Camino Ladrillo 16"}],
	["floor_road_ladrillo_17", {"category": "suelo", "label": "Camino Ladrillo 17"}],
	["floor_road_ladrillo_18", {"category": "suelo", "label": "Camino Ladrillo 18"}],
	["floor_road_ladrillo_19", {"category": "suelo", "label": "Camino Ladrillo 19"}],
	["floor_road_ladrillo_20", {"category": "suelo", "label": "Camino Ladrillo 20"}],
	["floor_road_ladrillo_21", {"category": "suelo", "label": "Camino Ladrillo 21"}],
	["floor_road_ladrillo_22", {"category": "suelo", "label": "Camino Ladrillo 22"}],
	["floor_road_ladrillo_23", {"category": "suelo", "label": "Camino Ladrillo 23"}],
	["floor_road_ladrillo_24", {"category": "suelo", "label": "Camino Ladrillo 24"}],
	["floor_road_ladrillo_25", {"category": "suelo", "label": "Camino Ladrillo 25"}],
	["floor_road_ladrillo_26", {"category": "suelo", "label": "Camino Ladrillo 26"}],
	["floor_road_ladrillo_27", {"category": "suelo", "label": "Camino Ladrillo 27"}],
	["floor_road_ladrillo_28", {"category": "suelo", "label": "Camino Ladrillo 28"}],
	["floor_road_ladrillo_29", {"category": "suelo", "label": "Camino Ladrillo 29"}],
	["floor_road_ladrillo_30", {"category": "suelo", "label": "Camino Ladrillo 30"}],
	["floor_road_ladrillo_31", {"category": "suelo", "label": "Camino Ladrillo 31"}],
	["floor_road_ladrillo_32", {"category": "suelo", "label": "Camino Ladrillo 32"}],
	["floor_road_ladrillo_33", {"category": "suelo", "label": "Camino Ladrillo 33"}],
	["floor_road_losa_01", {"category": "suelo", "label": "Camino Losa 1"}],
	["floor_road_losa_02", {"category": "suelo", "label": "Camino Losa 2"}],
	["floor_road_losa_03", {"category": "suelo", "label": "Camino Losa 3"}],
	["floor_road_losa_04", {"category": "suelo", "label": "Camino Losa 4"}],
	["floor_road_losa_05", {"category": "suelo", "label": "Camino Losa 5"}],
	["floor_road_losa_06", {"category": "suelo", "label": "Camino Losa 6"}],
	["floor_road_losa_07", {"category": "suelo", "label": "Camino Losa 7"}],
	["floor_road_losa_08", {"category": "suelo", "label": "Camino Losa 8"}],
	["floor_road_losa_09", {"category": "suelo", "label": "Camino Losa 9"}],
	["floor_road_losa_10", {"category": "suelo", "label": "Camino Losa 10"}],
	["floor_road_losa_11", {"category": "suelo", "label": "Camino Losa 11"}],
	["floor_road_losa_12", {"category": "suelo", "label": "Camino Losa 12"}],
	["floor_road_losa_13", {"category": "suelo", "label": "Camino Losa 13"}],
	["floor_road_losa_14", {"category": "suelo", "label": "Camino Losa 14"}],
	["floor_road_losa_15", {"category": "suelo", "label": "Camino Losa 15"}],
	["floor_road_losa_16", {"category": "suelo", "label": "Camino Losa 16"}],
	["floor_road_losa_17", {"category": "suelo", "label": "Camino Losa 17"}],
	["floor_road_losa_18", {"category": "suelo", "label": "Camino Losa 18"}],
	["floor_road_losa_19", {"category": "suelo", "label": "Camino Losa 19"}],
	["floor_road_losa_20", {"category": "suelo", "label": "Camino Losa 20"}],
	["floor_road_losa_21", {"category": "suelo", "label": "Camino Losa 21"}],
	["floor_road_losa_22", {"category": "suelo", "label": "Camino Losa 22"}],
	["floor_road_losa_23", {"category": "suelo", "label": "Camino Losa 23"}],
	["floor_road_losa_24", {"category": "suelo", "label": "Camino Losa 24"}],
	["floor_road_losa_25", {"category": "suelo", "label": "Camino Losa 25"}],
	["floor_road_losa_26", {"category": "suelo", "label": "Camino Losa 26"}],
	["floor_road_losa_27", {"category": "suelo", "label": "Camino Losa 27"}],
	["floor_road_losa_28", {"category": "suelo", "label": "Camino Losa 28"}],
	["floor_road_losa_29", {"category": "suelo", "label": "Camino Losa 29"}],
	["floor_road_losa_30", {"category": "suelo", "label": "Camino Losa 30"}],
	["floor_road_losa_31", {"category": "suelo", "label": "Camino Losa 31"}],
	["floor_road_losa_32", {"category": "suelo", "label": "Camino Losa 32"}],
	["floor_road_losa_33", {"category": "suelo", "label": "Camino Losa 33"}],
	["floor_road_losa_34", {"category": "suelo", "label": "Camino Losa 34"}],
	["floor_road_losa_35", {"category": "suelo", "label": "Camino Losa 35"}],
	["floor_road_losa_36", {"category": "suelo", "label": "Camino Losa 36"}],
	["floor_road_losa_37", {"category": "suelo", "label": "Camino Losa 37"}],
	["floor_road_losa_38", {"category": "suelo", "label": "Camino Losa 38"}],
	["floor_road_losa_39", {"category": "suelo", "label": "Camino Losa 39"}],
	["floor_road_losa_40", {"category": "suelo", "label": "Camino Losa 40"}],
	["floor_road_losa_41", {"category": "suelo", "label": "Camino Losa 41"}],
	["floor_road_losa_42", {"category": "suelo", "label": "Camino Losa 42"}],
	["floor_road_losa_43", {"category": "suelo", "label": "Camino Losa 43"}],
	["floor_road_losa_44", {"category": "suelo", "label": "Camino Losa 44"}],
	["floor_road_losa_45", {"category": "suelo", "label": "Camino Losa 45"}],
	["floor_road_losa_46", {"category": "suelo", "label": "Camino Losa 46"}],
	["floor_road_losa_47", {"category": "suelo", "label": "Camino Losa 47"}],
	["floor_road_losa_48", {"category": "suelo", "label": "Camino Losa 48"}],
	["floor_road_losa_49", {"category": "suelo", "label": "Camino Losa 49"}],
	["floor_road_losa_50", {"category": "suelo", "label": "Camino Losa 50"}],
	["floor_road_losa_51", {"category": "suelo", "label": "Camino Losa 51"}],
	["floor_road_losa_52", {"category": "suelo", "label": "Camino Losa 52"}],
	["floor_road_losa_53", {"category": "suelo", "label": "Camino Losa 53"}],
	["floor_road_losa_54", {"category": "suelo", "label": "Camino Losa 54"}],
	["floor_road_losa_55", {"category": "suelo", "label": "Camino Losa 55"}],
	["floor_road_losa_56", {"category": "suelo", "label": "Camino Losa 56"}],
	["floor_road_losa_57", {"category": "suelo", "label": "Camino Losa 57"}],
	["floor_road_madera_01", {"category": "suelo", "label": "Camino Madera 1"}],
	["floor_road_madera_02", {"category": "suelo", "label": "Camino Madera 2"}],
	["floor_road_madera_03", {"category": "suelo", "label": "Camino Madera 3"}],
	["floor_road_madera_04", {"category": "suelo", "label": "Camino Madera 4"}],
	["floor_road_madera_05", {"category": "suelo", "label": "Camino Madera 5"}],
	["floor_road_madera_06", {"category": "suelo", "label": "Camino Madera 6"}],
	["floor_road_madera_07", {"category": "suelo", "label": "Camino Madera 7"}],
	["floor_road_madera_08", {"category": "suelo", "label": "Camino Madera 8"}],
	["floor_road_madera_09", {"category": "suelo", "label": "Camino Madera 9"}],
	["floor_road_madera_10", {"category": "suelo", "label": "Camino Madera 10"}],
	["floor_road_madera_11", {"category": "suelo", "label": "Camino Madera 11"}],
	["floor_road_madera_12", {"category": "suelo", "label": "Camino Madera 12"}],
	["floor_road_madera_13", {"category": "suelo", "label": "Camino Madera 13"}],
	["floor_road_madera_14", {"category": "suelo", "label": "Camino Madera 14"}],
	["floor_road_madera_15", {"category": "suelo", "label": "Camino Madera 15"}],
	["floor_road_madera_16", {"category": "suelo", "label": "Camino Madera 16"}],
	["floor_road_madera_17", {"category": "suelo", "label": "Camino Madera 17"}],
	["floor_road_madera_18", {"category": "suelo", "label": "Camino Madera 18"}],
	["floor_road_piedra_01", {"category": "suelo", "label": "Camino Piedra 1"}],
	["floor_road_piedra_02", {"category": "suelo", "label": "Camino Piedra 2"}],
	["floor_road_piedra_03", {"category": "suelo", "label": "Camino Piedra 3"}],
	["floor_road_piedra_04", {"category": "suelo", "label": "Camino Piedra 4"}],
	["floor_road_piedra_05", {"category": "suelo", "label": "Camino Piedra 5"}],
	["floor_road_piedra_06", {"category": "suelo", "label": "Camino Piedra 6"}],
	["floor_road_piedra_07", {"category": "suelo", "label": "Camino Piedra 7"}],
	["floor_road_piedra_08", {"category": "suelo", "label": "Camino Piedra 8"}],
	["floor_road_piedra_09", {"category": "suelo", "label": "Camino Piedra 9"}],
	["floor_road_piedra_10", {"category": "suelo", "label": "Camino Piedra 10"}],
	["floor_road_piedra_11", {"category": "suelo", "label": "Camino Piedra 11"}],
	["floor_road_piedra_12", {"category": "suelo", "label": "Camino Piedra 12"}],
	["floor_road_piedra_13", {"category": "suelo", "label": "Camino Piedra 13"}],
	["floor_road_piedra_14", {"category": "suelo", "label": "Camino Piedra 14"}],
	["floor_road_piedra_15", {"category": "suelo", "label": "Camino Piedra 15"}],
	["floor_road_piedra_16", {"category": "suelo", "label": "Camino Piedra 16"}],
	["floor_road_piedra_17", {"category": "suelo", "label": "Camino Piedra 17"}],
	["floor_road_piedra_18", {"category": "suelo", "label": "Camino Piedra 18"}],
	["floor_road_piedra_19", {"category": "suelo", "label": "Camino Piedra 19"}],
	["floor_road_piedra_20", {"category": "suelo", "label": "Camino Piedra 20"}],
	["floor_road_piedra_21", {"category": "suelo", "label": "Camino Piedra 21"}],
	["floor_road_piedra_22", {"category": "suelo", "label": "Camino Piedra 22"}],
	["floor_road_piedra_23", {"category": "suelo", "label": "Camino Piedra 23"}],
	["floor_road_piedra_24", {"category": "suelo", "label": "Camino Piedra 24"}],
	["floor_road_piedra_25", {"category": "suelo", "label": "Camino Piedra 25"}],
	["floor_road_piedra_26", {"category": "suelo", "label": "Camino Piedra 26"}],
	["floor_road_piedra_27", {"category": "suelo", "label": "Camino Piedra 27"}],
	["floor_road_piedra_28", {"category": "suelo", "label": "Camino Piedra 28"}],
	["floor_road_piedra_29", {"category": "suelo", "label": "Camino Piedra 29"}],
	["floor_road_piedra_30", {"category": "suelo", "label": "Camino Piedra 30"}],
	["floor_road_piedra_31", {"category": "suelo", "label": "Camino Piedra 31"}],
	["floor_road_piedra_32", {"category": "suelo", "label": "Camino Piedra 32"}],
	["floor_road_piedra_33", {"category": "suelo", "label": "Camino Piedra 33"}],
	["floor_road_piedra_34", {"category": "suelo", "label": "Camino Piedra 34"}],
	["floor_road_piedra_35", {"category": "suelo", "label": "Camino Piedra 35"}],
	["floor_road_piedra_36", {"category": "suelo", "label": "Camino Piedra 36"}],
	["floor_road_piedra_37", {"category": "suelo", "label": "Camino Piedra 37"}],
	["floor_road_piedra_38", {"category": "suelo", "label": "Camino Piedra 38"}],
	["floor_road_piedra_39", {"category": "suelo", "label": "Camino Piedra 39"}],
	["floor_road_piedra_40", {"category": "suelo", "label": "Camino Piedra 40"}],
	["floor_road_piedra_41", {"category": "suelo", "label": "Camino Piedra 41"}],
	["floor_road_piedra_42", {"category": "suelo", "label": "Camino Piedra 42"}],
	["floor_road_piedra_43", {"category": "suelo", "label": "Camino Piedra 43"}],
	["floor_road_piedra_44", {"category": "suelo", "label": "Camino Piedra 44"}],
	["floor_road_piedra_45", {"category": "suelo", "label": "Camino Piedra 45"}],
	["floor_road_piedra_46", {"category": "suelo", "label": "Camino Piedra 46"}],
	["floor_road_piedra_47", {"category": "suelo", "label": "Camino Piedra 47"}],
	["floor_road_piedra_48", {"category": "suelo", "label": "Camino Piedra 48"}],
	["floor_road_piedra_49", {"category": "suelo", "label": "Camino Piedra 49"}],
	["floor_road_piedra_50", {"category": "suelo", "label": "Camino Piedra 50"}],
	["floor_pasto_01", {"category": "suelo", "label": "Plains Pasto 1"}],
	["floor_tierra_01", {"category": "suelo", "label": "Plains Tierra 1"}],
	["floor_tierra_02", {"category": "suelo", "label": "Plains Tierra 2"}],
	["floor_tierra_03", {"category": "suelo", "label": "Plains Tierra 3"}],
	["floor_tierra_04", {"category": "suelo", "label": "Plains Tierra 4"}],
	["floor_tierra_05", {"category": "suelo", "label": "Plains Tierra 5"}],
	["floor_tierra_06", {"category": "suelo", "label": "Plains Tierra 6"}],
	["floor_tierra_07", {"category": "suelo", "label": "Plains Tierra 7"}],
	["floor_tierra_08", {"category": "suelo", "label": "Plains Tierra 8"}],
	["floor_tierra_09", {"category": "suelo", "label": "Plains Tierra 9"}],
	["floor_tierra_10", {"category": "suelo", "label": "Plains Tierra 10"}],
	["floor_tierra_11", {"category": "suelo", "label": "Plains Tierra 11"}],
	["floor_tierra_12", {"category": "suelo", "label": "Plains Tierra 12"}],
	["floor_tierra_13", {"category": "suelo", "label": "Plains Tierra 13"}],
	["floor_estanque_01", {"category": "suelo", "label": "Plains Estanque 1"}],
	["floor_estanque_02", {"category": "suelo", "label": "Plains Estanque 2"}],
	["floor_estanque_03", {"category": "suelo", "label": "Plains Estanque 3"}],
	["floor_estanque_04", {"category": "suelo", "label": "Plains Estanque 4"}],
	["floor_estanque_05", {"category": "suelo", "label": "Plains Estanque 5"}],
	["floor_estanque_06", {"category": "suelo", "label": "Plains Estanque 6"}],
	["floor_estanque_07", {"category": "suelo", "label": "Plains Estanque 7"}],
	["floor_estanque_08", {"category": "suelo", "label": "Plains Estanque 8"}],
	["floor_estanque_09", {"category": "suelo", "label": "Plains Estanque 9"}],
	["floor_estanque_10", {"category": "suelo", "label": "Plains Estanque 10"}],
	["floor_estanque_11", {"category": "suelo", "label": "Plains Estanque 11"}],
	["floor_estanque_12", {"category": "suelo", "label": "Plains Estanque 12"}],
	["floor_estanque_13", {"category": "suelo", "label": "Plains Estanque 13"}],
	["floor_estanque_14", {"category": "suelo", "label": "Plains Estanque 14"}],
	["floor_estanque_15", {"category": "suelo", "label": "Plains Estanque 15"}],
	["floor_estanque_16", {"category": "suelo", "label": "Plains Estanque 16"}],
	["floor_puente_01", {"category": "suelo", "label": "Plains Puente 1"}],
	["floor_acantilado_01", {"category": "suelo", "label": "Plains Acantilado 1"}],
	["floor_acantilado_02", {"category": "suelo", "label": "Plains Acantilado 2"}],
	["floor_acantilado_03", {"category": "suelo", "label": "Plains Acantilado 3"}],
	["floor_acantilado_04", {"category": "suelo", "label": "Plains Acantilado 4"}],
	["floor_acantilado_05", {"category": "suelo", "label": "Plains Acantilado 5"}],
	["floor_acantilado_06", {"category": "suelo", "label": "Plains Acantilado 6"}],
	["floor_acantilado_07", {"category": "suelo", "label": "Plains Acantilado 7"}],
	["floor_acantilado_08", {"category": "suelo", "label": "Plains Acantilado 8"}],
	["floor_acantilado_09", {"category": "suelo", "label": "Plains Acantilado 9"}],
	["floor_acantilado_10", {"category": "suelo", "label": "Plains Acantilado 10"}],
	["floor_acantilado_11", {"category": "suelo", "label": "Plains Acantilado 11"}],
	["floor_acantilado_12", {"category": "suelo", "label": "Plains Acantilado 12"}],
	["floor_acantilado_13", {"category": "suelo", "label": "Plains Acantilado 13"}],
	["floor_acantilado_14", {"category": "suelo", "label": "Plains Acantilado 14"}],
	["floor_isla_01", {"category": "suelo", "label": "Plains Isla 1"}],
	["floor_isla_02", {"category": "suelo", "label": "Plains Isla 2"}],
	["floor_isla_03", {"category": "suelo", "label": "Plains Isla 3"}],
	["floor_isla_04", {"category": "suelo", "label": "Plains Isla 4"}],
	["floor_isla_05", {"category": "suelo", "label": "Plains Isla 5"}],
	["floor_isla_06", {"category": "suelo", "label": "Plains Isla 6"}],
	["floor_isla_07", {"category": "suelo", "label": "Plains Isla 7"}],
	["floor_isla_08", {"category": "suelo", "label": "Plains Isla 8"}],
	["floor_isla_09", {"category": "suelo", "label": "Plains Isla 9"}],
	["floor_isla_10", {"category": "suelo", "label": "Plains Isla 10"}],
	["floor_isla_11", {"category": "suelo", "label": "Plains Isla 11"}],
	["floor_orilla_01", {"category": "suelo", "label": "Plains Orilla 1"}],
	["decor_barrel", {"category": "decor", "label": "Barril"}],
	["decor_crate", {"category": "decor", "label": "Cajón"}],
	["decor_crate_stack", {"category": "decor", "label": "Cajones apilados"}],
	["decor_banner", {"category": "decor", "label": "Banderines"}],
	["decor_cart", {"category": "decor", "label": "Carreta"}],
	["decor_cart_wheel", {"category": "decor", "label": "Rueda de carreta"}],
	["decor_bush", {"category": "decor", "label": "Arbusto"}],
	["decor_spigot", {"category": "decor", "label": "Grifo de pared"}],
	["decor_fence", {"category": "decor", "label": "Cerca de madera"}],
	["decor_garden_bed", {"category": "decor", "label": "Jardinera"}],
	["decor_plank", {"category": "decor", "label": "Tabla de madera"}],
	["decor_stone_platform", {"category": "decor", "label": "Plataforma de piedra"}],
	["decor_door_wood", {"category": "decor", "label": "Puerta de madera (suelta)"}],
	["decor_dormer_red", {"category": "decor", "label": "Buhardilla roja (sobre techo)"}],
	["decor_dormer_blue", {"category": "decor", "label": "Buhardilla azul (sobre techo)"}],
	["decor_chimney_red", {"category": "decor", "label": "Chimenea roja"}],
	["decor_chimney_blue", {"category": "decor", "label": "Chimenea azul"}],
	["decor_roof_gable_red", {"category": "decor", "label": "Techo prefab rojo"}],
	["decor_roof_gable_blue", {"category": "decor", "label": "Techo prefab azul"}],
	["decor_plains_tree_oak", {"category": "decor", "label": "Plains: Roble"}],
	["decor_plains_tree_round", {"category": "decor", "label": "Plains: Árbol frondoso"}],
	["decor_plains_tree_pine", {"category": "decor", "label": "Plains: Pino"}],
	["decor_plains_stump", {"category": "decor", "label": "Plains: Tocón"}],
	["decor_plains_stump_axe", {"category": "decor", "label": "Plains: Tocón con hacha"}],
	["decor_plains_log_fallen", {"category": "decor", "label": "Plains: Tronco caído"}],
	["decor_plains_log_post", {"category": "decor", "label": "Plains: Poste de madera"}],
	["decor_plains_plank", {"category": "decor", "label": "Plains: Tabla"}],
	["decor_plains_bush", {"category": "decor", "label": "Plains: Arbusto"}],
	["decor_plains_bush_berry", {"category": "decor", "label": "Plains: Arbusto con bayas"}],
	["decor_plains_bush_fern", {"category": "decor", "label": "Plains: Helecho"}],
	["decor_plains_grass_tall", {"category": "decor", "label": "Plains: Pasto alto"}],
	["decor_plains_grass_tuft", {"category": "decor", "label": "Plains: Mata de pasto"}],
	["decor_plains_grass_tuft_b", {"category": "decor", "label": "Plains: Mata de pasto (b)"}],
	["decor_plains_wheat", {"category": "decor", "label": "Plains: Trigo"}],
	["decor_plains_rock", {"category": "decor", "label": "Plains: Roca"}],
	["decor_plains_rock_mossy", {"category": "decor", "label": "Plains: Roca con musgo"}],
	["decor_plains_mushrooms_red", {"category": "decor", "label": "Plains: Hongos rojos"}],
	["decor_plains_mushrooms_yellow", {"category": "decor", "label": "Plains: Hongos amarillos"}],
	["decor_plains_mushrooms_brown", {"category": "decor", "label": "Plains: Hongos marrones"}],
	["decor_plains_lilypad", {"category": "decor", "label": "Plains: Nenúfar"}],
	["decor_plains_barrel", {"category": "decor", "label": "Plains: Barril"}],
	["decor_plains_barrel_water", {"category": "decor", "label": "Plains: Barril con agua"}],
	["decor_plains_crate", {"category": "decor", "label": "Plains: Cajón"}],
	["decor_plains_sack", {"category": "decor", "label": "Plains: Bolsa"}],
	["decor_plains_sack_grain", {"category": "decor", "label": "Plains: Bolsa de grano"}],
	["decor_plains_sack_open", {"category": "decor", "label": "Plains: Bolsa abierta"}],
	["decor_plains_hay_bale", {"category": "decor", "label": "Plains: Fardo de heno"}],
	["decor_plains_cauldron", {"category": "decor", "label": "Plains: Caldero"}],
	["decor_plains_beehive", {"category": "decor", "label": "Plains: Colmena"}],
	["decor_plains_well", {"category": "decor", "label": "Plains: Pozo"}],
	["decor_plains_campfire", {"category": "decor", "label": "Plains: Fogata"}],
	["decor_plains_sign_wood", {"category": "decor", "label": "Plains: Cartel de madera"}],
	["decor_plains_sign_skull", {"category": "decor", "label": "Plains: Cartel con calavera"}],
	["decor_plains_stall_apples", {"category": "decor", "label": "Plains: Puesto de manzanas"}],
	["decor_plains_bench", {"category": "decor", "label": "Plains: Banco"}],
	["decor_plains_tent", {"category": "decor", "label": "Plains: Carpa"}],
	["decor_plains_wagon", {"category": "decor", "label": "Plains: Carromato"}],
	["decor_mega_beehive_skep_straw", {"category": "decor", "label": "Mega Pueblo: Beehive skep straw"}],
	["decor_mega_chicken_coop_wooden", {"category": "decor", "label": "Mega Pueblo: Chicken coop wooden"}],
	["decor_mega_clothesline_posts", {"category": "decor", "label": "Mega Pueblo: Clothesline posts"}],
	["decor_mega_dovecote_post_mounted", {"category": "decor", "label": "Mega Pueblo: Dovecote post mounted"}],
	["decor_mega_fence_wattle_segment", {"category": "decor", "label": "Mega Pueblo: Fence wattle segment"}],
	["decor_mega_firewood_pile_stacked", {"category": "decor", "label": "Mega Pueblo: Firewood pile stacked"}],
	["decor_mega_garden_plot_vegetables", {"category": "decor", "label": "Mega Pueblo: Garden plot vegetables"}],
	["decor_mega_grindstone_wheel_pedal", {"category": "decor", "label": "Mega Pueblo: Grindstone wheel pedal"}],
	["decor_mega_handcart_single_axle", {"category": "decor", "label": "Mega Pueblo: Handcart single axle"}],
	["decor_mega_hay_bale_round", {"category": "decor", "label": "Mega Pueblo: Hay bale round"}],
	["decor_mega_hay_cart_two_wheel", {"category": "decor", "label": "Mega Pueblo: Hay cart two wheel"}],
	["decor_mega_outdoor_oven_clay", {"category": "decor", "label": "Mega Pueblo: Outdoor oven clay"}],
	["decor_mega_rain_barrel_wooden", {"category": "decor", "label": "Mega Pueblo: Rain barrel wooden"}],
	["decor_mega_shrine_roadside_stone", {"category": "decor", "label": "Mega Pueblo: Shrine roadside stone"}],
	["decor_mega_signpost_wooden_blank", {"category": "decor", "label": "Mega Pueblo: Signpost wooden blank"}],
	["decor_mega_water_well_roof", {"category": "decor", "label": "Mega Pueblo: Water well roof"}],
	["decor_mega_barrel_water_open", {"category": "decor", "label": "Mega Aldea: Barrel water open"}],
	["decor_mega_basket_woven_apples", {"category": "decor", "label": "Mega Aldea: Basket woven apples"}],
	["decor_mega_basket_woven_empty", {"category": "decor", "label": "Mega Aldea: Basket woven empty"}],
	["decor_mega_bench_rough_plank", {"category": "decor", "label": "Mega Aldea: Bench rough plank"}],
	["decor_mega_broom_twig_standing", {"category": "decor", "label": "Mega Aldea: Broom twig standing"}],
	["decor_mega_chicken_feed_trough", {"category": "decor", "label": "Mega Aldea: Chicken feed trough"}],
	["decor_mega_chopping_block_axe", {"category": "decor", "label": "Mega Aldea: Chopping block axe"}],
	["decor_mega_clay_pot_group", {"category": "decor", "label": "Mega Aldea: Clay pot group"}],
	["decor_mega_hay_pile_loose", {"category": "decor", "label": "Mega Aldea: Hay pile loose"}],
	["decor_mega_log_pile_short", {"category": "decor", "label": "Mega Aldea: Log pile short"}],
	["decor_mega_milk_churn_lidded", {"category": "decor", "label": "Mega Aldea: Milk churn lidded"}],
	["decor_mega_pitchfork_leaning_stand", {"category": "decor", "label": "Mega Aldea: Pitchfork leaning stand"}],
	["decor_mega_sack_grain_tied", {"category": "decor", "label": "Mega Aldea: Sack grain tied"}],
	["decor_mega_sack_pile_leaning", {"category": "decor", "label": "Mega Aldea: Sack pile leaning"}],
	["decor_mega_scarecrow_cross_frame", {"category": "decor", "label": "Mega Aldea: Scarecrow cross frame"}],
	["decor_mega_stone_pile_field", {"category": "decor", "label": "Mega Aldea: Stone pile field"}],
	["decor_mega_wash_tub_board", {"category": "decor", "label": "Mega Aldea: Wash tub board"}],
	["decor_mega_wheelbarrow_wooden", {"category": "decor", "label": "Mega Aldea: Wheelbarrow wooden"}],
	["decor_mega_wooden_bucket_rope", {"category": "decor", "label": "Mega Aldea: Wooden bucket rope"}],
	["decor_mega_wooden_stool_three_leg", {"category": "decor", "label": "Mega Aldea: Wooden stool three leg"}],
	["decor_mega_door_double_barn", {"category": "decor", "label": "Mega Arquitectura: Door double barn"}],
	["decor_mega_door_wooden_iron_hinges", {"category": "decor", "label": "Mega Arquitectura: Door wooden iron hinges"}],
	["decor_mega_fence_picket_segment", {"category": "decor", "label": "Mega Arquitectura: Fence picket segment"}],
	["decor_mega_floor_cobblestone_road", {"category": "decor", "label": "Mega Arquitectura: Floor cobblestone road"}],
	["decor_mega_floor_dirt_path", {"category": "decor", "label": "Mega Arquitectura: Floor dirt path"}],
	["decor_mega_floor_stone_slab_interior", {"category": "decor", "label": "Mega Arquitectura: Floor stone slab interior"}],
	["decor_mega_floor_wood_plank_interior", {"category": "decor", "label": "Mega Arquitectura: Floor wood plank interior"}],
	["decor_mega_gate_town_arch_wooden", {"category": "decor", "label": "Mega Arquitectura: Gate town arch wooden"}],
	["decor_mega_roof_thatch_edge_strip", {"category": "decor", "label": "Mega Arquitectura: Roof thatch edge strip"}],
	["decor_mega_wall_brick_medieval", {"category": "decor", "label": "Mega Arquitectura: Wall brick medieval"}],
	["decor_mega_wall_ivy_overgrown", {"category": "decor", "label": "Mega Arquitectura: Wall ivy overgrown"}],
	["decor_mega_wall_log_horizontal", {"category": "decor", "label": "Mega Arquitectura: Wall log horizontal"}],
	["decor_mega_wall_low_stone_field", {"category": "decor", "label": "Mega Arquitectura: Wall low stone field"}],
	["decor_mega_wall_stone_rough", {"category": "decor", "label": "Mega Arquitectura: Wall stone rough"}],
	["decor_mega_wall_timber_frame_plaster", {"category": "decor", "label": "Mega Arquitectura: Wall timber frame plaster"}],
	["decor_mega_window_shuttered_wall", {"category": "decor", "label": "Mega Arquitectura: Window shuttered wall"}],
	["decor_mega_amphora_group_leaning", {"category": "decor", "label": "Mega Mercado: Amphora group leaning"}],
	["decor_mega_banner_pole_pennant", {"category": "decor", "label": "Mega Mercado: Banner pole pennant"}],
	["decor_mega_barrel_pickles_open", {"category": "decor", "label": "Mega Mercado: Barrel pickles open"}],
	["decor_mega_cage_chickens_wooden", {"category": "decor", "label": "Mega Mercado: Cage chickens wooden"}],
	["decor_mega_cheese_wheel_stack", {"category": "decor", "label": "Mega Mercado: Cheese wheel stack"}],
	["decor_mega_coin_chest_small_open", {"category": "decor", "label": "Mega Mercado: Coin chest small open"}],
	["decor_mega_counter_butcher_hanging", {"category": "decor", "label": "Mega Mercado: Counter butcher hanging"}],
	["decor_mega_crate_produce_stack", {"category": "decor", "label": "Mega Mercado: Crate produce stack"}],
	["decor_mega_hanging_scale_brass", {"category": "decor", "label": "Mega Mercado: Hanging scale brass"}],
	["decor_mega_notice_board_standing", {"category": "decor", "label": "Mega Mercado: Notice board standing"}],
	["decor_mega_rug_market_woven", {"category": "decor", "label": "Mega Mercado: Rug market woven"}],
	["decor_mega_spice_sacks_open_row", {"category": "decor", "label": "Mega Mercado: Spice sacks open row"}],
	["decor_mega_stall_bread_baskets", {"category": "decor", "label": "Mega Mercado: Stall bread baskets"}],
	["decor_mega_stall_canopy_fabric_rolls", {"category": "decor", "label": "Mega Mercado: Stall canopy fabric rolls"}],
	["decor_mega_stall_canopy_pottery", {"category": "decor", "label": "Mega Mercado: Stall canopy pottery"}],
	["decor_mega_stall_canopy_vegetables", {"category": "decor", "label": "Mega Mercado: Stall canopy vegetables"}],
	["decor_mega_stall_fish_table_ice", {"category": "decor", "label": "Mega Mercado: Stall fish table ice"}],
	["decor_mega_table_goods_cloth", {"category": "decor", "label": "Mega Mercado: Table goods cloth"}],
	["decor_mega_torch_post_market", {"category": "decor", "label": "Mega Mercado: Torch post market"}],
	["decor_mega_weighing_table_balance", {"category": "decor", "label": "Mega Mercado: Weighing table balance"}],
	["decor_mega_bar_counter_corner", {"category": "decor", "label": "Mega Taberna: Bar counter corner"}],
	["decor_mega_bar_counter_straight", {"category": "decor", "label": "Mega Taberna: Bar counter straight"}],
	["decor_mega_bard_stool_lute", {"category": "decor", "label": "Mega Taberna: Bard stool lute"}],
	["decor_mega_barrel_ale_tapped", {"category": "decor", "label": "Mega Taberna: Barrel ale tapped"}],
	["decor_mega_bench_long_matching", {"category": "decor", "label": "Mega Taberna: Bench long matching"}],
	["decor_mega_candelabra_standing", {"category": "decor", "label": "Mega Taberna: Candelabra standing"}],
	["decor_mega_chair_ladder_back", {"category": "decor", "label": "Mega Taberna: Chair ladder back"}],
	["decor_mega_chandelier_wheel_candles", {"category": "decor", "label": "Mega Taberna: Chandelier wheel candles"}],
	["decor_mega_fireplace_stone_hearth", {"category": "decor", "label": "Mega Taberna: Fireplace stone hearth"}],
	["decor_mega_food_platter_bread_cheese", {"category": "decor", "label": "Mega Taberna: Food platter bread cheese"}],
	["decor_mega_innkeeper_ledger_stand", {"category": "decor", "label": "Mega Taberna: Innkeeper ledger stand"}],
	["decor_mega_keg_rack_triple", {"category": "decor", "label": "Mega Taberna: Keg rack triple"}],
	["decor_mega_long_table_plank", {"category": "decor", "label": "Mega Taberna: Long table plank"}],
	["decor_mega_mug_group_wooden", {"category": "decor", "label": "Mega Taberna: Mug group wooden"}],
	["decor_mega_round_table_small", {"category": "decor", "label": "Mega Taberna: Round table small"}],
	["decor_mega_rug_tavern_worn", {"category": "decor", "label": "Mega Taberna: Rug tavern worn"}],
	["decor_mega_serving_tray_mugs", {"category": "decor", "label": "Mega Taberna: Serving tray mugs"}],
	["decor_mega_stew_pot_hanging", {"category": "decor", "label": "Mega Taberna: Stew pot hanging"}],
	["decor_mega_trophy_stag_head_plaque", {"category": "decor", "label": "Mega Taberna: Trophy stag head plaque"}],
	["decor_mega_wine_shelf_bottles", {"category": "decor", "label": "Mega Taberna: Wine shelf bottles"}],
	["decor_mega_anvil_horn_block", {"category": "decor", "label": "Mega Herrería: Anvil horn block"}],
	["decor_mega_armor_stand_breastplate", {"category": "decor", "label": "Mega Herrería: Armor stand breastplate"}],
	["decor_mega_bellows_large_lever", {"category": "decor", "label": "Mega Herrería: Bellows large lever"}],
	["decor_mega_cart_wheel_repair_leaning", {"category": "decor", "label": "Mega Herrería: Cart wheel repair leaning"}],
	["decor_mega_chain_bundle_hook", {"category": "decor", "label": "Mega Herrería: Chain bundle hook"}],
	["decor_mega_coal_pile_shovel", {"category": "decor", "label": "Mega Herrería: Coal pile shovel"}],
	["decor_mega_forge_stone_coal_glow", {"category": "decor", "label": "Mega Herrería: Forge stone coal glow"}],
	["decor_mega_grinding_wheel_water", {"category": "decor", "label": "Mega Herrería: Grinding wheel water"}],
	["decor_mega_hammer_set_bench", {"category": "decor", "label": "Mega Herrería: Hammer set bench"}],
	["decor_mega_helmet_row_shelf", {"category": "decor", "label": "Mega Herrería: Helmet row shelf"}],
	["decor_mega_horseshoe_crate_full", {"category": "decor", "label": "Mega Herrería: Horseshoe crate full"}],
	["decor_mega_ingot_stack_iron", {"category": "decor", "label": "Mega Herrería: Ingot stack iron"}],
	["decor_mega_quench_barrel_steam", {"category": "decor", "label": "Mega Herrería: Quench barrel steam"}],
	["decor_mega_scrap_metal_bin", {"category": "decor", "label": "Mega Herrería: Scrap metal bin"}],
	["decor_mega_shield_stack_leaning", {"category": "decor", "label": "Mega Herrería: Shield stack leaning"}],
	["decor_mega_sword_finished_table", {"category": "decor", "label": "Mega Herrería: Sword finished table"}],
	["decor_mega_tool_wall_board_tongs", {"category": "decor", "label": "Mega Herrería: Tool wall board tongs"}],
	["decor_mega_weapon_rack_polearms", {"category": "decor", "label": "Mega Herrería: Weapon rack polearms"}],
	["decor_mega_weapon_rack_swords", {"category": "decor", "label": "Mega Herrería: Weapon rack swords"}],
	["decor_mega_workbench_smith_vise", {"category": "decor", "label": "Mega Herrería: Workbench smith vise"}],
	["decor_mega_boulder_moss_large", {"category": "decor", "label": "Mega Naturaleza: Boulder moss large"}],
	["decor_mega_bridge_wooden_arch", {"category": "decor", "label": "Mega Naturaleza: Bridge wooden arch"}],
	["decor_mega_bush_berry_red", {"category": "decor", "label": "Mega Naturaleza: Bush berry red"}],
	["decor_mega_bush_round_green", {"category": "decor", "label": "Mega Naturaleza: Bush round green"}],
	["decor_mega_fallen_log_moss", {"category": "decor", "label": "Mega Naturaleza: Fallen log moss"}],
	["decor_mega_flower_patch_wild", {"category": "decor", "label": "Mega Naturaleza: Flower patch wild"}],
	["decor_mega_grass_tuft_tall", {"category": "decor", "label": "Mega Naturaleza: Grass tuft tall"}],
	["decor_mega_ivy_patch_ground", {"category": "decor", "label": "Mega Naturaleza: Ivy patch ground"}],
	["decor_mega_lantern_post_iron", {"category": "decor", "label": "Mega Naturaleza: Lantern post iron"}],
	["decor_mega_mushroom_ring_brown", {"category": "decor", "label": "Mega Naturaleza: Mushroom ring brown"}],
	["decor_mega_oak_tree_round_crown", {"category": "decor", "label": "Mega Naturaleza: Oak tree round crown"}],
	["decor_mega_pine_tree_tall", {"category": "decor", "label": "Mega Naturaleza: Pine tree tall"}],
	["decor_mega_pond_small_lily", {"category": "decor", "label": "Mega Naturaleza: Pond small lily"}],
	["decor_mega_rock_group_small", {"category": "decor", "label": "Mega Naturaleza: Rock group small"}],
	["decor_mega_stream_stepping_stones", {"category": "decor", "label": "Mega Naturaleza: Stream stepping stones"}],
	["decor_mega_tree_stump_axe_rings", {"category": "decor", "label": "Mega Naturaleza: Tree stump axe rings"}],
	["decor_mega_banner_hanging_blank", {"category": "decor", "label": "Mega Aventura: Banner hanging blank"}],
	["decor_mega_barrel_gunpowder_marked", {"category": "decor", "label": "Mega Aventura: Barrel gunpowder marked"}],
	["decor_mega_brazier_iron_standing", {"category": "decor", "label": "Mega Aventura: Brazier iron standing"}],
	["decor_mega_cage_iron_hanging", {"category": "decor", "label": "Mega Aventura: Cage iron hanging"}],
	["decor_mega_campfire_ring_pot", {"category": "decor", "label": "Mega Aventura: Campfire ring pot"}],
	["decor_mega_cart_covered_wagon", {"category": "decor", "label": "Mega Aventura: Cart covered wagon"}],
	["decor_mega_crate_weapons_open", {"category": "decor", "label": "Mega Aventura: Crate weapons open"}],
	["decor_mega_gallows_post_rope", {"category": "decor", "label": "Mega Aventura: Gallows post rope"}],
	["decor_mega_pillory_stocks_wooden", {"category": "decor", "label": "Mega Aventura: Pillory stocks wooden"}],
	["decor_mega_potion_shelf_bottles", {"category": "decor", "label": "Mega Aventura: Potion shelf bottles"}],
	["decor_mega_quest_board_parchment_blank", {"category": "decor", "label": "Mega Aventura: Quest board parchment blank"}],
	["decor_mega_scroll_pile_desk", {"category": "decor", "label": "Mega Aventura: Scroll pile desk"}],
	["decor_mega_tent_canvas_small", {"category": "decor", "label": "Mega Aventura: Tent canvas small"}],
	["decor_mega_torch_wall_bracket", {"category": "decor", "label": "Mega Aventura: Torch wall bracket"}],
	["decor_mega_treasure_chest_closed", {"category": "decor", "label": "Mega Aventura: Treasure chest closed"}],
	["decor_mega_treasure_chest_open_gold", {"category": "decor", "label": "Mega Aventura: Treasure chest open gold"}],
	["building_house_small_a", {"category": "building", "label": "Casa chica (paja)"}],
	["building_house_small_b", {"category": "building", "label": "Casa chica (piedra)"}],
	["building_house_small_c", {"category": "building", "label": "Casa chica (terracota)"}],
	["building_house_small_d", {"category": "building", "label": "Casa chica (cabaña)"}],
	["building_house_small_e", {"category": "building", "label": "Casa chica (azul)"}],
	["building_house_small_f", {"category": "building", "label": "Casa chica (musgo)"}],
	["building_house_medium_common_a", {"category": "building", "label": "Casa mediana (blanca)"}],
	["building_house_medium_common_b", {"category": "building", "label": "Casa mediana (troncos)"}],
	["building_house_medium_common_c", {"category": "building", "label": "Casa mediana (piedra)"}],
	["building_house_medium_common_d", {"category": "building", "label": "Casa mediana (azul)"}],
	["building_house_medium_common_e", {"category": "building", "label": "Casa mediana (ocre)"}],
	["building_house_medium_noble", {"category": "building", "label": "Casa mediana (noble)"}],
	["building_house_medium_mage", {"category": "building", "label": "Casa mediana (mágica)"}],
	["building_house_medium_gothic", {"category": "building", "label": "Casa mediana (gótica)"}],
	["building_house_medium_cozy", {"category": "building", "label": "Casa mediana (rosales)"}],
	["building_house_large_common", {"category": "building", "label": "Casa grande (común)"}],
	["building_house_large_noble", {"category": "building", "label": "Casa grande (noble)"}],
	["building_house_large_mage", {"category": "building", "label": "Casa grande (mágica)"}],
	["building_house_large_gothic", {"category": "building", "label": "Casa grande (gótica)"}],
	["building_house_large_cozy", {"category": "building", "label": "Casa grande (rosales)"}],
	["building_house_grand_common", {"category": "building", "label": "Casona (común)"}],
	["building_house_grand_noble", {"category": "building", "label": "Casona (noble)"}],
	["building_house_grand_mage", {"category": "building", "label": "Casona (mágica)"}],
	["building_house_grand_gothic", {"category": "building", "label": "Casona (gótica)"}],
	["building_house_grand_cozy", {"category": "building", "label": "Casona (rosales)"}],
	["building_house_palace_common", {"category": "building", "label": "Palacio (gremial)"}],
	["building_house_palace_noble", {"category": "building", "label": "Palacio (noble)"}],
	["building_house_palace_mage", {"category": "building", "label": "Palacio (mágico)"}],
	["building_house_palace_gothic", {"category": "building", "label": "Palacio (gótico)"}],
	["building_house_palace_cozy", {"category": "building", "label": "Palacio (rosales)"}],
	["building_mansion", {"category": "building", "label": "Mansión"}],
	["building_blacksmith", {"category": "building", "label": "Herrería"}],
	["building_bank", {"category": "building", "label": "Banco"}],
	["building_inn", {"category": "building", "label": "Posada"}],
	["building_temple", {"category": "building", "label": "Templo"}],
	["building_general_goods", {"category": "building", "label": "Tienda: artículos generales"}],
	["building_market_produce", {"category": "building", "label": "Mercado: verdulería"}],
	["building_market_textiles", {"category": "building", "label": "Mercado: telas"}],
	["building_market_spices", {"category": "building", "label": "Mercado: especias"}],
	["building_dock", {"category": "building", "label": "Muelle"}],
	["collision_block", {"category": "collision", "label": "Bloquear celda"}],
]


static func label_for(id: String) -> String:
	for entry in ENTRIES:
		if str(entry[0]) == id:
			return str(entry[1].get("label", id))
	return id


## Ids belonging to one category, in palette order.
static func ids_in_category(category: String) -> Array[String]:
	var out: Array[String] = []
	for entry in ENTRIES:
		if str(entry[1].get("category", "")) == category:
			out.append(str(entry[0]))
	return out


## Flat list of every placeable id, in the order the whole palette (and the
## 1-9 hotbar) presents them: category order, then entry order within it.
static func all_ids() -> Array[String]:
	var out: Array[String] = []
	for cat in CATEGORIES:
		out.append_array(ids_in_category(str(cat[0])))
	return out
