class_name RoadAutotileTable
extends RefCounted
## GENERATED by tools/bake_road_autotile.py -- do not hand-edit.
##
## Blob mask -> road tile, per style, derived from the tiles' own alpha
## channels. Read RoadAutotiler (which consumes this) for what the masks
## mean and how a mask with no entry here is resolved, and the baker's
## docstring for how the art is measured.
##
## Each entry is [tile id, alternative-tile transform bits]. A non-zero
## transform is a mirror of a tile the style does ship, standing in for a
## piece it doesn't (TileSetAtlasSource.TRANSFORM_FLIP_H / _FLIP_V).
##
## Styles the pack has art for but that are NOT offered as a brush,
## because their edge pieces do not repeat along their own run -- the
## pack draws them as framed platforms, so a long road comes out as
## stacked boxes. Worst run seam, against a budget of 100:
##   losa       183
##   madera     121
## They stay paintable piece by piece under SUELO. Re-slice their
## art with repeating middles and they come back automatically.

const STYLES: Array[String] = ["adoquin", "ladrillo", "piedra"]

const TABLE := {
	"adoquin": {
		"fill": "road_adoquin_02", # best of 5, self-seam 16 (worst 31)
		# edges repeat along their run, worst seam 50.
		"round": {
			1: ["road_adoquin_47", 0], # cap, road to N
			7: ["road_adoquin_09", 0], # corner, road to N and E
			16: ["road_adoquin_44", 0], # cap, road to S
			28: ["road_adoquin_01", 0], # corner, road to E and S
			31: ["road_adoquin_48", 0], # west edge
			112: ["road_adoquin_03", 0], # corner, road to S and W
			124: ["road_adoquin_42", 0], # north edge
			127: ["road_adoquin_15", 0], # inner corner, no road NW
			193: ["road_adoquin_41", 0], # corner, road to W and N
			199: ["road_adoquin_43", 0], # south edge
			223: ["road_adoquin_30", 0], # inner corner, no road SW
			241: ["road_adoquin_49", 0], # east edge
			247: ["road_adoquin_14", 0], # inner corner, no road SE
			253: ["road_adoquin_20", 0], # inner corner, no road NE
		},
		"diag": {
			7: ["road_adoquin_26", 0], # corner, road to N and E
			28: ["road_adoquin_23", 0], # corner, road to E and S
			112: ["road_adoquin_24", 0], # corner, road to S and W
			193: ["road_adoquin_27", 0], # corner, road to W and N
		},
	},
	"ladrillo": {
		"fill": "road_ladrillo_12", # best of 10, self-seam 83 (worst 145)
		# edges repeat along their run, worst seam 73.
		"round": {
			1: ["road_ladrillo_30", 0], # cap, road to N
			7: ["road_ladrillo_08", 0], # corner, road to N and E
			16: ["road_ladrillo_28", 0], # cap, road to S
			28: ["road_ladrillo_01", 0], # corner, road to E and S
			31: ["road_ladrillo_32", 0], # west edge
			112: ["road_ladrillo_03", 0], # corner, road to S and W
			124: ["road_ladrillo_25", 0], # north edge
			193: ["road_ladrillo_09", 0], # corner, road to W and N
			199: ["road_ladrillo_27", 0], # south edge
			241: ["road_ladrillo_33", 0], # east edge
		},
		"diag": {
			7: ["road_ladrillo_18", 0], # corner, road to N and E
			28: ["road_ladrillo_14", 0], # corner, road to E and S
			112: ["road_ladrillo_15", 0], # corner, road to S and W
			193: ["road_ladrillo_19", 0], # corner, road to W and N
		},
	},
	"piedra": {
		"fill": "road_piedra_20", # best of 5, self-seam 19 (worst 23)
		# edges repeat along their run, worst seam 23.
		"round": {
			1: ["road_piedra_48", 0], # cap, road to N
			7: ["road_piedra_30", 0], # corner, road to N and E
			16: ["road_piedra_45", 0], # cap, road to S
			28: ["road_piedra_16", 0], # corner, road to E and S
			31: ["road_piedra_49", 0], # west edge
			112: ["road_piedra_03", 0], # corner, road to S and W
			124: ["road_piedra_42", 0], # north edge
			127: ["road_piedra_07", 0], # inner corner, no road NW
			193: ["road_piedra_29", 0], # corner, road to W and N
			199: ["road_piedra_42", 8192], # south edge
			223: ["road_piedra_14", 0], # inner corner, no road SW
			241: ["road_piedra_50", 0], # east edge
			247: ["road_piedra_11", 0], # inner corner, no road SE
			253: ["road_piedra_06", 0], # inner corner, no road NE
		},
		"diag": {
			7: ["road_piedra_28", 0], # corner, road to N and E
			28: ["road_piedra_22", 0], # corner, road to E and S
			112: ["road_piedra_37", 0], # corner, road to S and W
			193: ["road_piedra_27", 0], # corner, road to W and N
		},
	},
}
